routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('profile', 'ProfileController')->only(['edit', 'update', 'destroy'])->middleware('auth');
Route::get('profile/pause/{profile}', 'ProfileController@pause')->name('profile.pause')->middleware('auth');
Route::put('profile/continue/{profile}', 'ProfileController@continue')->name('profile.continue')->middleware('auth');
Route::resource('add-donor', 'AddDonorController')->only(['create','store', 'edit', 'update', 'destroy'])->middleware(['admin', 'auth']);

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'phone', 'password', 'gotWell', 'blood', 'status'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/AddDonorController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class AddDonorController extends Controller
{
    public function __construct()
    {
        $this->middleware('admin');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('createDonor');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name' => ['required', 'string', 'max:255'],
            'phone' => ['unique:users','required', 'max:11', 'min:11'],
            'password' => ['required', 'string', 'min:4', 'confirmed'],
        ]);

        User::create([
            'role' => $request->role,
            'name' => $request->name,
            'phone' => $request->phone,
            'password' => Hash::make($request->password),
            'blood' => isset($request['blood']) ? $request['blood'] : null,
            'gotWell' => isset($request['gotWell']) ? $request['gotWell'] : now(),
        ]);

        return redirect(route('home'))->with('success', 'আপনি নতুন একজন দাতা এড করেছেন');
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $donor = User::findOrFail($id);

        return view('editDonor')->with('donor', $donor);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $donor = User::findOrFail($id);

        $this->validate($request, [
            'name' => ['required', 'string', 'max:255'],
            'phone' => ['unique:users,phone,'.$donor->id,'required', 'max:11', 'min:11'],
        ]);

        $donor->update([
            'name' => $request->name,
            'phone' => $request->phone,
            'blood' => isset($request['blood']) ? $request['blood'] : null,
            'role' => $request->role
        ]);

        return redirect(route('home'))->with('success', 'আপনি দাতার প্রোফাইল আপডেট করেছেন');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
//        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $users = User::whereNotNull('blood')->get();
        return view('home')->with('users', $users);
    }
}

app/Http/Controllers/ProfileController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;

class ProfileController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);
        return view('edit')->with('user',$user);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::findOrFail($id);

        $this->validate($request, [
            'name' => 'required',
            'phone' => 'required|string|min:11|max:11|unique:users,phone,'.$user->id,
        ]);

        $user->update([
            'name' => $request->name,
            'phone' => $request->phone,
            'blood' => $request->blood,
            'gotWell' => isset($request->gotWell) ? $request->gotWell : now() ,
        ]);

        return redirect(route('home'))->with('success', 'আপনার প্রোফাইল টি আপডেট হয়েছে');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);

        $user->delete();

        return redirect('/');
    }

    public function pause(Request $request, $id)
    {
        $user = User::findOrFail($id);

        $user->update([
            'blood' => null
        ]);

        return redirect(route('home'))->with('warning', 'তালিকা থেকে আপনার নাম্বার মুছা হল!  আবার তালিকায় ফিরে আসতে চাইলে ম্যানেজ প্রোফাইল থেকে আবার ফিরে আসুন বাটন চাপুন');
    }

    public function continue(Request $request, $id)
    {
        $user = User::findOrFail($id);

        $this->validate($request, [
            'blood' => 'required'
        ]);

        $user->update([
            'blood' => $request->blood,
        ]);

        return redirect(route('home'))->with('success', 'আপনার নাম্বার পুনরায় তালিকাভুক্ত হল');
    }
}

resources/views/home.blade.php
@extends('layouts.master')

@section('content')
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h5 class="m-0 text-success">রক্তের গ্রুপ দিয়ে সার্চ করুন</h5>
                        </div><!-- /.col -->
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="{{ route('home') }}">Home</a></li>
                                <li class="breadcrumb-item active">User</li>
                            </ol>
                        </div><!-- /.col -->
                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->

        <!-- Main content -->
            <section class="content">
                <div class="container-fluid">
                    @if (session('success'))
                        <div class="alert alert-success">
                            {{ session('success') }}
                        </div>
                    @endif
                        @if (session('warning'))
                        <div class="alert alert-warning">
                            {{ session('warning') }}
                        </div>
                    @endif
                    <!-- Main row -->
                    <div class="row">
                        <!-- Left col -->
                        <section class="col-lg-12">
                            <!-- Custom tabs (Charts with tabs)-->
                            <div class="card">
                                <div class="card-header bg-dark font-weight-bold">
                                    দাতাদের তালিকা
                                    @auth()
                                        @if(Auth::user()->role === 'admin')
                                            <a class="btn btn-success btn-sm float-right" href="{{ route('add-donor.create') }}">পরিচিত প্লাজমা দাতা এড করুন</a>
                                        @else
                                        @endif
                                    @else

                                    @endauth

                                </div><!-- /.card-header -->
                                <div class="card-body">
                                    <table id="example1" class="table table-bordered table-striped">
                                        <thead>
                                        <tr>
                                            <th>আইডি</th>
                                            <th>নাম</th>
                                            <th>ফোন</th>
                                            <th>রক্তের গ্রুপ</th>
                                            <th>সুস্থ হওয়ার তারিখ</th>
                                            @auth()
                                                @if(Auth::user()->role === 'admin')
                                                    <th>একশন</th>
                                                @else

                                                @endif
                                            @else

                                            @endauth
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach($users as $user)
                                            <tr>
                                                <td>{{ $user->id }}</td>
                                                <td>{{ $user->name }}</td>
                                                <td>{{ $user->phone }}</td>
                                                <td>{{ $user->blood }}</td>
                                                <td>{{ date('d-m-Y', strtotime($user->gotWell)) }}</td>
                                                @auth()
                                                    @if(Auth::user()->role == 'admin')
                                                        <td>
                                                            <a title="edit" class="btn btn-primary btn-sm ml-3" href="{{ route('add-donor.edit', $user->id) }}"><i class="fas fa-user-edit"></i></a>
                                                            <button title="delete" type="submit" class="btn btn-danger btn-sm ml-5" onclick="handleDelete({{ $user->id }})"><i class="fas fa-trash"></i></button>
                                                        </td>
                                                    @else

                                                    @endif

                                                @else

                                                @endauth
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                </div><!-- /.card-body -->
                                <form action="" method="POST" id="deleteProfileForm">
                                @method('DELETE')
                                @csrf
                                <!-- Modal -->
                                    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="deleteModalLabel">প্রোফাইল ডিলিট</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    আপনি কি এই প্রোফাইলটি পুরোপুরি ডিলিট করতে চান ?
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">না</button>
                                                    <button type="submit" class="btn btn-danger">হ্যা, ডিলিট</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                                <!-- Modal -->
                                <form action="" method="POST" id="continueProfileForm">
                                    @method('PUT')
                                    @csrf
                                    <div class="modal fade" id="continueModal" tabindex="-1" role="dialog" aria-labelledby="continueModalLabel" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="continueModalLabel">প্রোফাইল পুনরায় তালিকাভুক্ত করুন</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    <div class="form-group">
                                                        <label for="blood">রক্তের গ্রুপ <span class="text-danger">(প্লাজমা দাতা হলে)</span></label>
                                                        <select class="form-control" id="blood" name="blood" required>
                                                            <option value="">Select</option>
                                                            <option value="O+">O+</option>
                                                            <option value="O-">O-</option>
                                                            <option value="A+">A+</option>
                                                            <option value="A-">A-</option>
                                                            <option value="B+">B+</option>
                                                            <option value="B-">B-</option>
                                                            <option value="AB+">AB+</option>
                                                            <option value="AB-">AB-</option>
                                                        </select>
                                                        @error('blood')
                                                            <span class="invalid-feedback" role="alert">
                                                                <strong>{{ $message }}</strong>
                                                            </span>
                                                        @enderror
                                                    </div>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">বাতিল</button>
                                                    <button type="submit" class="btn btn-success">প্রোফাইল চালু করুন</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                            <!-- /.card -->
                            <!-- /.card -->
                        </section>
                        <!-- right col -->
                    </div>
                    <!-- /.row (main row) -->
                </div><!-- /.container-fluid -->
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->

@endsection

@section('css')
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{ asset('') }}/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="{{ asset('') }}/dist/css/adminlte.min.css">
{{--    <!-- overlayScrollbars -->--}}
{{--    <link rel="stylesheet" href="{{ asset('') }}/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">--}}
    <!-- DataTables -->
    <link rel="stylesheet" href="{{ asset('') }}/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="{{ asset('') }}/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
{{--    <!--  Google Font: Source Sans Pro -->--}}
{{--    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">--}}
@endsection

@section('script')
    <!-- jQuery -->
    <script src="{{ asset('') }}/plugins/jquery/jquery.min.js"></script>
{{--    <!-- jQuery UI 1.11.4 -->--}}
{{--    <script src="{{ asset('') }}/plugins/jquery-ui/jquery-ui.min.js"></script>--}}
{{--    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->--}}
{{--    <script>--}}
{{--        $.widget.bridge('uibutton', $.ui.button)--}}
{{--    </script>--}}
{{--    --}}{{--    Popper JS--}}
{{--    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>--}}
    <!-- Bootstrap 4 -->
    <script src="{{ asset('') }}/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- AdminLTE App -->
    <script src="{{ asset('') }}/dist/js/adminlte.js"></script>

    <!-- DataTables -->
    <script src="{{ asset('') }}/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="{{ asset('') }}/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="{{ asset('') }}/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="{{ asset('') }}/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>

    <script>
        $(function () {
            $("#example1").DataTable({
                "responsive": true,
                "autoWidth": false,
            });
        });
    </script>
    <script>
        function handleDelete($id) {
            var form = document.getElementById('deleteProfileForm')
            form.action = '/profile/' + $id
            $('#deleteModal').modal('show')
        }
    </script>
    <script>
        function handleContinue($id) {
            var form = document.getElementById('continueProfileForm')
            form.action = '/profile/continue/' + $id
            $('#continueModal').modal('show')
        }
    </script>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Plasma') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

{{--    <!-- Fonts -->--}}
{{--    <link rel="dns-prefetch" href="//fonts.gstatic.com">--}}
{{--    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">--}}

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    {{--    Date picker--}}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
</head>
<body style="background-color: #E7B124">
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-dark bg-success shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link text-dark lead" href="{{ route('login') }}">লগইন</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link text-dark lead" href="{{ route('register') }}">রেজিস্ট্রেশন</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script>
        flatpickr('#gotWell');

    </script>
</body>
</html>

resources/views/layouts/master.blade.php
@include('partials.header')

@auth @include('partials.sidebar') @elseauth "" @endauth

@yield('content')

@include('partials.footer')

resources/views/partials/footer.blade.php
<footer class="main-footer">
    <b>Developed by</b> <a href="https://facebook.com/arifurrahmanbd">Arifur Rahman</a>
    <div class="float-right d-none d-sm-inline-block">
    </div>
</footer>

@yield('script')

</div>
</body
</html>

resources/views/partials/sidebar.blade.php
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{{ route('home') }}" class="brand-link">
        <img src="{{ asset('') }}dist/img/logo.jpg" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
             style="opacity: .8">
        <span class="brand-text font-weight-light">Plasma</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                     with font-awesome or any other icon font library -->
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
                             with font-awesome or any other icon font library -->
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link active">
                                <p>
                                    <i class="fas fa-user mr-2"></i>
                                    ম্যানেজ প্রোফাইল
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="{{ route('profile.edit', Auth::user()->id) }}" class="nav-link">
                                        <i class="fas fa-edit text-primary nav-icon"></i>
                                        <p>প্রোফাইল এডিট করুন</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="{{ route('profile.pause', Auth::user()->id) }}" class="nav-link">
                                        <i class="fas fa-pause text-warning nav-icon"></i>
                                        <p>লিস্ট থেকে প্রোফাইল মুছুন</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="#" class="nav-link" onclick="handleContinue({{ Auth::user()->id }})">
                                        <i class="fas fa-play text-success nav-icon"></i>
                                        <p>লিস্টে আবার ফিরে আসুন</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="#" class="nav-link active" onclick="handleDelete({{ Auth::user()->id }})">
                                        <i class="fas fa-trash text-danger nav-icon"></i>
                                        <p>প্রোফাইল ডিলিট করুন</p>
                                    </a>
                                </li>
                            </ul>
                    <li class="nav-item has-treeview">
                        <a class="nav-link bg-danger mt-2" href="{{ route('logout') }}"
                           onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                            <i class="fas fa-sign-out-alt mr-2"></i>
                            <p>লগ আউট</p>
                        </a>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    </li>
            </ul>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>